import json,statistics,datetime,hashlib
from pathlib import Path
p=Path(__file__).resolve().parent;s=json.loads((p/'summary.json').read_text());micro=json.loads((p/'micro-summary.json').read_text());inter=json.loads((p/'interaction.json').read_text());load=json.loads((p/'load-summary.json').read_text());wire=json.loads((p/'e/wire-results.json').read_text());records=json.loads((p/'verified-records.json').read_text());formal=[x for x in records if not x['warmup']]
f=lambda x:f'{x:.2f}'
lines=['# 批次大小与压缩交叉测试报告','', '结论：扩大批次降低了独立 Arrow IPC 编解码 CPU 成本，但没有带来稳定的端到端提速。现有证据支持存在批次相关开销，不支持将压缩函数调用次数认定为当前整体性能的主要瓶颈。保留当前默认 8192 行、无压缩配置，不依据本轮结果切换生产部署。','', '## 测试口径','', '- 2026-09-15，R=140.210.239.53:10023，E=:10025；隔离目录 deploy/fgac-batch-compression，Flight 18820–18828。原有 18815 与旧部署保持运行。','- 8192 / 32768 / 65536 行 × NONE / LZ4 / Zstd level 1，两个场景，九配置共用一个 R Spark JVM 和一个 E Spark JVM。每条扫描在相同位置设置 batch_rows，实际批次数验证生效。','- Bob90% 返回 2,011,899 行；Bob 授权集合100%返回 2,234,632 行，后者不是原始数据全表100%。四列与原测试一致。','- 每个场景/配置预热8次、正式36次，共144次预热＋648次正式查询。四个9轮区块采用随机循环排列，每配置在每个执行位置出现次数相同。种子91504，无提前停止或删样本。','- 完整四列 count＋双 xxhash64 摘要消费和关闭流均在端到端计时内；所有结果匹配之前 Ranger 原生查询的行数、摘要和 schema。快照固定6896028106384817739，开始、每9轮、结束校验。','- 本轮用于识别批次与压缩的作用，没有重新测量 Ranger 延迟，因此不输出新的 FGAC 对 Ranger 劣化率，也不判断是否达到5%目标。','- 保持原local[2]、2 GiB堆配置与R额外计算资源，不加CPU配额或绑核。保持2批/16 MiB预取队列；批次扩大后实际字节占用随之增加，这是本实验无法单独剥离的因素。','- 置信区间采用4000次循环块bootstrap，块长3；另保存块长9敏感性结果。为探索性比较，未作多重比较校正，且并非多次独立JVM重启实验。','', '## 端到端结果','', '正数表示更慢。百分比为同轮配对比值的平均值，不能由表中耗时中位数相除复算。','', '| 场景 | 模式 | 耗时中位数 ms | 相对同codec 8192行变化 | 95%区间 | 实际批次数 |','|---|---|---:|---:|---|---:|']
for x in s:lines.append(f"| {x['case']} | {x['mode']} | {f(x['total_ms'])} | {f(x['vs_same_codec_8192_pct'])}% | [{f(x['vs_same_codec_8192_ci'][0])}, {f(x['vs_same_codec_8192_ci'][1])}]% | {x['batches']} |")
lines+=['','## 扣除无压缩变化：压缩额外成本是否下降？','','计算：(大批压缩 − 大批无压缩) − (8192压缩 − 8192无压缩)。负值代表压缩相对成本下降。全部区间含零；块长9敏感性分析也全部含零。不能证明整体压缩额外成本稳定改善，也不能据此证明两者等效。','','| 场景 | codec | 批次行数 | 额外成本变化 ms | 95%区间 ms |','|---|---|---:|---:|---|']
for x in inter:lines.append(f"| {x['case']} | {x['codec']} | {x['size']} | {f(x['change_in_compression_extra_ms'])} | [{f(x['ci'][0])}, {f(x['ci'][1])}] |")
lines+=['','## 独立 IPC 编解码测试','','在正式查询完成后，用实际 Bob100% 数据在 E 内存中合并列块并重新分批。每组合4次预热＋36次正式测量，共360次；编码、解码分别计时，完整值相等性在计时外校验。无Spark扫描、跨机网络与摘要计算，不能把这里的时间当成端到端关键路径时间。内存中重新分批没有保留原Spark分区边界，所以批次数为273/69/35，与真实传输275/70/36略有不同。','','| codec | 行/批 | 非空输入缓冲区数 | 编码CPU ms | 解码CPU ms | 编码墙钟 ms | 解码墙钟 ms |','|---|---:|---:|---:|---:|---:|---:|']
for x in micro:lines.append(f"| {x['codec']} | {x['size']} | {int(x['nonempty_input_buffers'])} | {f(x['encode_cpu_ms'])} | {f(x['decode_cpu_ms'])} | {f(x['encode_ms'])} | {f(x['decode_ms'])} |")
lines+=['','8192→65536行，非空缓冲区数1092→140，减少87.2%；编码CPU与解码CPU中位数之和：LZ4约232→189ms（减少18.7%），Zstd约498→429ms（减少13.7%）。对应编码和解码墙钟中位数之和约节省14ms/24ms。中位数之和不是合并阶段耗时的中位数。','','这些度量包括 Arrow 序列化、分配、线程调度与 codec 工作，不是直接采集的 codec 函数调用次数或纯函数CPU。因而能证明批次大小影响编解码成本，但无法将收益全部归因于函数调用固定开销。缓冲区数减少近八倍，CPU只下降约一至两成，也不支持“减少调用次数即可解决主要成本”的判断。','','## 为什么局部下降没有转化为整体提速？','','授权集合100%下，首批到达中位数：LZ4约421→442ms，Zstd约421→439ms，无压缩约418→444ms。较大批次伴随首批到达后移，不仅出现在压缩模式。R任务运行时间之和也有增加：LZ4约761→803ms、Zstd约757→795ms；任务GC时间之和中位数约7.5→14ms。这些是伴随变化，尚不能精确归因于分配、收集或调度。','','更少的压缩单元并未消除R分区级收集、JVM/Python IPC和E端消费；流水线各阶段重叠，不能把独立编解码节省与首批延迟直接相减，或把各探针耗时相加。继续扩大到整个分区没有得到本轮实验支持。','','## 实际 TCP 接收字节','','正式测试和微基准后，独立运行每场景每组合2次完整Flight读取，通过连接存活时 ss bytes_received 验证实际TCP接收字节。包括控制RPC和gRPC帧，不含链路/IP/TCP头开销；此阶段没有Spark摘要，耗时不计入性能报告。以下为Bob100%两次中位数。','','| codec | 8192行 | 32768行 | 65536行 |','|---|---:|---:|---:|']
for codec in ['NONE','LZ4','ZSTD']:
 vals=[statistics.median(x['tcp_received_bytes'] for x in wire if x['mode']==f'{codec}_{size}' and x['case']=='bob_100') for size in [8192,32768,65536]];lines.append('| '+codec+' | '+' | '.join(f'{x:,.0f}' for x in vals)+' |')
lines+=['','Zstd的大批次进一步减小传输量，LZ4的大批次传输量却略有增加，压缩率并不随批次大小统一单调改善。两者均没有稳定端到端收益。','','## 负载与可靠性','','| 主机 | 正式窗口平均CPU | 约2秒采样峰值 | 平均iowait | 换入/换出页 |','|---|---:|---:|---:|---:|']
for role,x in load.items():lines.append(f"| {role} | {f(x['cpu_mean_pct'])}% | {f(x['cpu_peak_pct'])}% | {x['iowait_mean_pct']:.6f}% | {x['swapin_pages']}/{x['swapout_pages']} |")
lines+=['','R侧观察到Doris及多个非本测试Java进程活动，E侧有MinIO、Milvus、容器服务等。R单核采样峰值约99%，不能用整机平均负载低来排除局部竞争。所有样本保留；两秒进程差分可能遗漏短命进程，不据此声称完全无干扰。交错平衡顺序降低了固定顺序偏差，但不能消除背景噪声或替代独立重复。','','全部792次查询与结果校验通过；9个无效身份负向测试通过；1584个E/R查询组无任务/作业失败、无内存或磁盘spill。原快照保持一致。详细指标见 stage-validation.json、load-summary.json、interaction.json。','','## 部署状态和建议','','仅新增隔离测试脚本与端点，没有新增核心代码修改或更改原服务默认配置。测试结束后E worker停止；R隔离进程组SIGTERM后Java退出，Python因多端点关闭未退出，核实命令路径后仅终止该隔离Python。原FGAC PID与旧服务启动标识保持一致，旧Catalog、Remote、MinIO健康检查均200；存储仍仅staging/warehouse。','','建议维持8192行作为当前配置。下一步优先细化R分区收集结束、JVM→Python首批交付、Flight首次写出、E首次可计算的时间线，再评估消除分区级等待的方案。若继续研究压缩，应测纯codec/分配/线程调度的独立成本，而不是直接把分区作为压缩块。','','图：batch_compression.png / batch_compression.pdf。原始证据：evidence-R.tar.gz、evidence-E.tar.gz；分析与测试脚本同目录。']
(p/'BATCH_COMPRESSION_REPORT.md').write_text('\n'.join(lines),encoding='utf-8')
