import json,statistics
from pathlib import Path
p=Path(__file__).resolve().parent
S=json.loads((p/'summary.json').read_text());M=json.loads((p/'metrics.json').read_text());O=json.loads((p/'overall.json').read_text());P=json.loads((p/'probe-summary.json').read_text());V=json.loads((p/'stage-validation.json').read_text());L=json.loads((p/'load-summary.json').read_text())
lines=['# 0.1% / 1% 四方法隔离与独立重启复测','', '本次针对此前小结果集结论反转，比较旧COLLECT、新STREAM、真实Ranger原生基线与INLINE。只改变测试部署与对照组织，没有再次修改FGAC算法。','', '## 口径与隔离','', '- 三轮独立重启；每轮四个独立E Spark/Python会话，COLLECT与STREAM各有独立R Spark/Python服务。R端18840/18841，方法间不共享SparkContext、JIT、Arrow队列；E临时目录按方法隔离，R按轮次/方法隔离。','- 测试查询串行交错；四方法24种顺序每场景各出现2次，每轮48组。场景顺序随机，每轮种子91601/91602/91603；启动顺序轮换，预热顺序随机。','- 每轮每方法80次预热，0.1%/1%各40次；每轮320次预热、384次正式查询，三轮合计960次预热、1152次正式查询。没有根据结果改变预热量、提前停止或剔除慢样本。','- 同一Iceberg快照6896028106384817739、四列、行策略与业务条件；count及双xxhash64全量摘要均在计时内。每轮权限负向检查、前中后快照检查、Ranger策略前后不变。','- E均local[2]/2GiB，FGAC各自额外使用R local[2]/2GiB；不设置总CPU配额或绑核。8192行批次、无压缩，消费者相同。COLLECT与STREAM只切换远端交付实现。','- 共用物理主机、MinIO、Polaris/Catalog和Ranger服务，保留正常暖缓存；未清空OS缓存，也未停止原业务。进程隔离不等于主机/共享缓存完全隔离。','- **本轮只混合两个小结果集场景；旧报告混合八个场景。** 因此本轮是针对性复现，不是将旧实验全部条件固定后的单变量重跑，不能将跨报告差值全归因于算法。','', '## 各次重启结果','', '耗时为中位数；百分比是同轮配对比值的平均。负值表示前者更快。95%区间用每轮3000次循环块bootstrap，块长4；不把144组当成144次独立部署。','', '| 重启 | 场景 | Native ms | Inline ms | COLLECT ms | STREAM ms | STREAM/Native | COLLECT/Native | STREAM/COLLECT |','|---|---|---:|---:|---:|---:|---:|---:|---:|']
for run in range(1,4):
 for case,label in [('bob_001','0.1%'),('bob_01','1%')]:
  m={x['mode']:x for x in M if x['run']==run and x['case']==case};s={x['comparison']:x for x in S if x['run']==run and x['case']==case}
  values=[f"{m[k]['total_ms']:.2f}" for k in ['NATIVE','INLINE','COLLECT','STREAM']]+[f"{s[k]['paired_mean_pct']:+.2f}%" for k in ['STREAM_vs_NATIVE','COLLECT_vs_NATIVE','STREAM_vs_COLLECT']]
  lines.append('| '+str(run)+' | '+label+' | '+' | '.join(values)+' |')
lines+=['','![独立重启配对区间](isolated_comparison.png)','','三次重启等权平均如下；仅三次重启，不用一个狭窄的合并区间掩盖轮间差异。','','| 场景 | STREAM/Native | COLLECT/Native | STREAM/COLLECT | STREAM/Inline |','|---|---:|---:|---:|---:|']
for case,label in [('bob_001','0.1%'),('bob_01','1%')]:
 o={x['comparison']:x for x in O if x['case']==case};lines.append('| '+label+' | '+' | '.join(f"{o[k]['restart_equal_mean_pct']:+.2f}%" for k in ['STREAM_vs_NATIVE','COLLECT_vs_NATIVE','STREAM_vs_COLLECT','STREAM_vs_INLINE'])+' |')
lines+=['','## 首批与分区探针','','| 重启 | 场景 | 批数 | Arrow逻辑字节 | 首批早于首分区完成 | 提前量中位数 ms |','|---|---|---:|---:|---:|---:|']
for x in P:lines.append(f"| {x['run']} | {x['case']} | {x['batches']:.0f} | {x['arrow_bytes']:.0f} | {x['write_before_partition_done']}/{x['n']} | {x['first_partition_lead_ms']:.3f} |")
lines+=['','0.1%只有3批，1%只有4批，均来自3个源分区。大结果集原先的分区内部多批等待在这里大幅缩小；首批提前也不保证最终完成提前，因为仍需等剩余分区及E端完整消费。Arrow逻辑字节不能替代TCP通信字节，本轮没有新增逐连接字节探针。','','## 校验与负载','',f"Spark事件校验覆盖{V['query_groups']}个E/R查询组，失败任务/作业{V['failed_tasks_or_jobs']}，内存spill {V['memory_spill_bytes']:.0f}字节，磁盘spill {V['disk_spill_bytes']:.0f}字节。所有结果及schema一致，四方法计时区间无重叠。",'', '| 角色 | 重启 | 主机CPU均值 | 峰值 | iowait均值 | swap-in/out页 |','|---|---|---:|---:|---:|---:|']
for x in L:lines.append(f"| {x['role']} | {x['run']} | {x['cpu_mean_pct']:.2f}% | {x['cpu_peak_pct']:.2f}% | {x['iowait_mean_pct']:.5f}% | {x['swapin_pages']}/{x['swapout_pages']} |")
lines+=['','以上为整机平均，不证明没有单核、GC/JIT或短时调度干扰。后台进程证据保留在load-summary.json及原始资源采样。每轮测试进程均退出后才启动下一轮；最终隔离端口关闭，原服务PID和健康状态保持正常，E配置哈希不变。','','## 复现材料','', '- benchmark.py / worker.py / manage_r.py / serve_compression.py：启动及对照脚本。','- summary.json / pairs.csv / metrics.json：各轮配对差异、分段结果与阶段耗时。','- stage-summary.json / stage-validation.json / probe-summary.json：Spark任务与交付探针。','- r/、e/：每轮查询记录、协议、顺序、快照、权限控制和清理证据。','- 大体积任务事件及全进程采样保留在R `/data1/lyb/fgac-lab/runs/alignment-isolated-0915/` 与E `/home/lyb/fgac-lab/runs/alignment-isolated-0915/` 的evidence-R/E.tar.gz；取回、解压到本地r/e后运行analyze.py、analyze_stages.py、analyze_load.py和aggregate.py。凭据不发布。','']
(p/'ISOLATED_ALIGNMENT_REPORT.md').write_text('\n'.join(lines),encoding='utf-8',newline='\n')

interpret=json.loads((p/'interpretation.json').read_text(encoding='utf-8'));f=p/'ISOLATED_ALIGNMENT_REPORT.md';t=f.read_text(encoding='utf-8').replace('## 口径与隔离',interpret['conclusions_markdown']+'## 口径与隔离').replace('## 校验与负载',interpret['diagnostic_markdown']+'## 校验与负载');f.write_text(t,encoding='utf-8',newline='\n')
