import json,statistics
from pathlib import Path
p=Path(__file__).resolve().parent
S=json.loads((p/'summary.json').read_text());M=json.loads((p/'metrics.json').read_text());O=json.loads((p/'overall.json').read_text());G=json.loads((p/'group-summary.json').read_text());GO=json.loads((p/'group-overall.json').read_text());T=json.loads((p/'restart-timing.json').read_text());V=json.loads((p/'stage-validation.json').read_text());L=json.loads((p/'load-summary.json').read_text());cases=json.loads((p/'cases.json').read_text())
labels={'bob_001':'Bob 0.1%','bob_01':'Bob 1%','bob_10':'Bob 10%','bob_50':'Bob 50%','bob_90':'Bob 90%','bob_100':'Bob授权100%','alice_original':'Alice原场景','whole_source_100':'原始全表100%'}
lines=['# 八场景、四方法、三次独立重启全量复测','', '本次恢复全部8个场景，比较最新STREAM、旧COLLECT、真实Ranger原生基线及INLINE；每轮结束确认测试进程退出后，等待至少5分钟再重启。未修改FGAC算法或引入结果缓存。','', '## 三轮汇总','', '百分比为同轮配对耗时比值的平均，负数表示前者更快。先对场景等权，再对三次重启等权；另保存耗时加权结果。不能把不同轮次耗时交叉相除。','', '| 组别 | 第一轮STREAM/Native | 第二轮 | 第三轮 | 三轮等权平均 |','|---|---:|---:|---:|---:|']
for group,label in [('all8','全部8场景'),('high2','90%及授权100%'),('small2','0.1%及1%'),('whole_source','原始全表100%')]:
 x=next(x for x in GO if x['group']==group and x['comparison']=='STREAM_vs_NATIVE');lines.append('| '+label+' | '+' | '.join(f'{v:+.2f}%' for v in x['restart_values']+[x['three_restart_mean_pct']])+' |')
lines+=['','## 各场景稳定性','', '| 场景 | 第一轮STREAM/Native | 第二轮 | 第三轮 | 三轮平均 | STREAM/COLLECT三轮平均 | STREAM/INLINE三轮平均 |','|---|---:|---:|---:|---:|---:|---:|']
for c in cases:
 name=c['name'];vals=[next(x for x in S if x['run']==run and x['case']==name and x['comparison']=='STREAM_vs_NATIVE')['paired_mean_pct'] for run in [1,2,3]];o={x['comparison']:x for x in O if x['case']==name};vals+=[o[k]['restart_equal_mean_pct'] for k in ['STREAM_vs_NATIVE','STREAM_vs_COLLECT','STREAM_vs_INLINE']];lines.append('| '+labels[name]+' | '+' | '.join(f'{v:+.2f}%' for v in vals)+' |')
lines+=['','![各场景三轮对照](full_comparison.png)','','图示95%区间为每次重启内部3000次循环块bootstrap，块长4；summary.json同时保存块长8敏感性分析。区间不代表跨环境保证，也没有针对所有场景的多重比较做校正。只进行3次独立重启，因此同时展示轮间方向和幅度，不用窄的合并区间代替重复部署证据。','','## 各轮耗时','', '| 重启 | 场景 | Native中位数ms | INLINE中位数ms | COLLECT中位数ms | STREAM中位数ms | STREAM/Native 95%区间 |','|---|---|---:|---:|---:|---:|---|']
for run in [1,2,3]:
 for c in cases:
  name=c['name'];m={x['mode']:x for x in M if x['run']==run and x['case']==name};x=next(x for x in S if x['run']==run and x['case']==name and x['comparison']=='STREAM_vs_NATIVE');lo,hi=x['ci_block4'];lines.append('| '+str(run)+' | '+labels[name]+' | '+' | '.join(f"{m[k]['total_ms']:.2f}" for k in ['NATIVE','INLINE','COLLECT','STREAM'])+f' | [{lo:+.2f}%, {hi:+.2f}%] |')
lines+=['','## 测试口径与方法隔离','', '- 每轮48组×8场景×4方法=1536次正式查询，三轮4608次；每轮6个E会话各80次预热，共480次，三轮1440次。每场景四方法24种排列各出现2次，顺序随机且不同重启使用不同种子91901/91902/91903。','- E端COLLECT、STREAM、INLINE各有独立Spark/Python进程；Native按Bob、Alice、bench_full分成3个独立授权会话。R端COLLECT、STREAM各自独立Spark/Python、端点18844/18845、临时目录和事件日志，未共享SparkContext或Arrow队列。E临时目录按方法/身份隔离。','- 查询串行交错执行；每轮结束后全部E/R测试进程退出，再等待5分钟，再创建新进程。不是复用上一轮已预热JVM。','- 同一Iceberg快照6896028106384817739；原生采用Spark3.5.8＋Kyuubi AuthZ1.10.2＋Ranger2.5.0，执行真实行权限重写；INLINE将等价策略写入SQL，是非安全等价参照。Polaris与MinIO保持原部署。','- 四列VendorID、trip_distance、fare_amount、payment_type完整消费；count与双xxhash64摘要、流完成与关闭均计入耗时。所有预热及正式结果校验；每轮前中后验证快照，Ranger策略前后不变，并验证原生拒绝未授权用户、FGAC拒绝无效令牌。','- 最新STREAM与旧COLLECT均8192行/批、无压缩、相同消费者；E均local[2]/2GiB，FGAC另有R local[2]/2GiB。不限制总算力、不绑核，R额外算力属于接受的部署形态优势。','- 共用物理主机、存储与Catalog服务，保留正常暖缓存，不清除OS缓存或停止原业务。进程隔离不等于物理主机及共享缓存完全隔离，5分钟间隔也不等于冷缓存。','- 选择率指返回/授权集合；Bob授权100%约占原始表75.4%，与原始全表100%区分。此次恢复8场景混合，不能直接与此前仅0.1%/1%混合的平均值拼接。','', '## 五分钟间隔核验','', '| 前一轮 | 停止后至下一轮启动s | 单调时钟等待s |','|---|---:|---:|']
for a,b in zip(T,T[1:]):lines.append(f"| {a['run']} | {b['start_epoch']-a['all_test_processes_stopped_epoch']:.3f} | {a['wait_monotonic_seconds']:.3f} |")
lines+=['','restart-timing.json保存控制端起止时间与单调时钟时长；两段等待均从测试进程确认退出之后计时。是否满300秒以单调时钟判断，墙钟校时和分辨率可能产生毫秒级差异；下一轮启动请求晚于等待结束。等待期间不运行测试查询，正常后台业务与被动采样仍存在。','','## 完整性与负载','',f"Spark事件覆盖{V['query_groups']}个查询组；失败任务/作业{V['failed_tasks_or_jobs']}，内存spill {V['memory_spill_bytes']:.0f}字节、磁盘spill {V['disk_spill_bytes']:.0f}字节。全部正式结果一致。",'', '| 角色 | 重启 | 主机CPU均值 | 峰值 | iowait均值 | 换入/换出页 |','|---|---|---:|---:|---:|---:|']
for x in L:lines.append(f"| {x['role']} | {x['run']} | {x['cpu_mean_pct']:.2f}% | {x['cpu_peak_pct']:.2f}% | {x['iowait_mean_pct']:.5f}% | {x['swapin_pages']}/{x['swapout_pages']} |")
lines+=['','原业务服务健康与PID、E配置哈希已核验；测试进程和端口已清理。整机平均CPU不能排除局部核心、GC/JIT或短时调度影响，详细进程采样与各轮任务指标保留为证据。','','## 复现与证据','', '- controller.py：三轮启动、清理、完整300秒等待及证据导出；SSH凭据通过交互输入，不写入脚本。','- benchmark.py、worker.py、manage_r.py、serve_compression.py：方法隔离、查询顺序与统一计时。','- summary.json / pairs.csv / group-summary.json / metrics.json：配对统计、分段结果及阶段耗时。','- stage-summary.json / stage-validation.json / probe-summary.json：Spark任务及交付证据。','- restart-timing.json / protocol-validation.json：间隔、顺序、快照与结果检查。','- 大体积证据在R `/data1/lyb/fgac-lab/runs/full-alignment-0915/`、E `/home/lyb/fgac-lab/runs/full-alignment-0915/` 的evidence-R/E.tar.gz。解压至本地r/e后依次运行analyze.py、analyze_stages.py、analyze_load.py、aggregate.py、analyze_groups.py、plot.py、make_report.py。依赖既有部署的Spark/Polaris/Ranger及受保护凭据。','']
(p/'FULL_RESTART_REPORT.md').write_text('\n'.join(lines),encoding='utf-8',newline='\n')

interp=json.loads((p/'interpretation.json').read_text(encoding='utf-8'));f=p/'FULL_RESTART_REPORT.md';t=f.read_text(encoding='utf-8').replace('## 三轮汇总',interp['conclusions']+'## 三轮汇总').replace('## 完整性与负载',interp['diagnosis']+'## 完整性与负载');f.write_text(t,encoding='utf-8',newline='\n')
