import json,statistics,datetime
from pathlib import Path
p=Path(__file__).resolve().parent;s=json.loads((p/'summary.json').read_text());overall=json.loads((p/'overall.json').read_text());load=json.loads((p/'load-summary.json').read_text());done=json.loads((p/'e/formal/done.json').read_text());stage=json.loads((p/'stage-validation.json').read_text());cases=json.loads((p/'e/formal/cases.json').read_text());by={x['case']:x for x in s}
labels={'bob_001':'Bob 0.1%','bob_01':'Bob 1%','bob_10':'Bob 10%','bob_50':'Bob 50%','bob_90':'Bob 90%','bob_100':'Bob授权集合100%','alice_original':'Alice fare >= 50','whole_source_100':'原始全表100%'}
fmt=lambda x:f'{x:+.2f}%'
lines=['# 最新FGAC、Ranger原生基线与inline统一性能报告','', '本报告仅使用2026-09-15同一轮交错测试，FGAC为分区内逐批交付、8192行批次、无压缩。原生基线为Spark＋Kyuubi AuthZ＋Apache Ranger；inline显式写入相同策略条件，是非安全等价的理想参照。','', '## 当前结论','', f"八场景等权配对平均FGAC相对原生变化为 **{fmt(overall['all8']['equal_case_mean_pct'])}**，95%块bootstrap区间 [{overall['all8']['ci_block3'][0]:+.2f}%, {overall['all8']['ci_block3'][1]:+.2f}%]。负数表示FGAC更快，正数表示劣化。",'', f"高返回率两场景等权变化为 **{fmt(overall['high2']['equal_case_mean_pct'])}**；原始全表100%场景变化为 **{fmt(by['whole_source_100']['fgac_vs_native_pct'])}**。低返回比例结果应逐项查看，不能用总体平均代替。",'', '## 统一口径','', '- R=140.210.239.53:10023，E=:10025。FGAC使用隔离单端点18832；只测试最新逐批交付方案，未混入JSON、落盘Parquet或旧COLLECT路径。','- R与E均Spark3.5.8、Java11，Iceberg1.7.2、Arrow19.0.1；元数据由Polaris1.7.0管理，同一MinIO与Iceberg快照6896028106384817739。','- Native：E通过Kyuubi AuthZ1.10.2和Ranger2.5.0进行真实权限检查和行策略重写；SQL只包含业务条件。使用AuthZ插件，并非本轮新增完整Kyuubi SQL/Thrift服务。','- Inline：E关闭该授权插件，在SQL中显式加入等价行条件，仍通过相同Polaris访问数据。它不能提供独立授权保证，也不保证每次测量都是最快。','- FGAC：Catalog授权/重校验、R执行策略与业务子计划、分区内Arrow交付、E消费。外部Flight协议、策略语义与结果列不变。','- 每条路径均完整消费VendorID、trip_distance、fare_amount、payment_type四列；count与两组xxhash64摘要、流完成和关闭均计入端到端时间。不是count-only，也没有把摘要移出计时。','- 每个E会话完成80次预热，五个会话随机轮流执行，合计400次，避免预热后长时间闲置。正式36轮×8场景×3路径=864次；六种路径顺序各出现6次，场景顺序随机，种子91509。','- Native按alice/bob/bench_full使用独立持久JVM，FGAC与inline各使用独立持久JVM，合计五个；均沿用E local[2]/2 GiB堆。FGAC另有R local[2]/2 GiB，不限制总CPU或绑核。这是明确接受的部署优势；local[2]不意味着含GC/JIT的进程总CPU最多两核。','- 使用正常元数据/策略缓存，不启用DataFrame或结果缓存。开始、每10轮和结束校验快照；Ranger策略前后完全一致；负向控制验证原生拒绝未授权用户、FGAC拒绝无效令牌。','- 所有预热/正式结果与历史原生完整摘要一致，且每轮三个路径互相验证。选择率指返回行数/授权集合行数；Bob授权集合100%约占原始表75.4%，与原始全表100%区分。','', '## 各场景结果','', '耗时为中位数；变化为同轮配对比值的平均值，不能由中位数直接相除复算。区间为5000次循环块bootstrap、块长3；另保存块长6敏感性分析。','', '| 场景 | 返回行数 | Native ms | FGAC ms | Inline ms | FGAC / Native变化 | 95%区间 | FGAC / Inline变化 |','|---|---:|---:|---:|---:|---:|---|---:|']
for x in s:lines.append(f"| {labels[x['case']]} | {x['rows']:,} | {x['native_ms']:.2f} | {x['fgac_ms']:.2f} | {x['inline_ms']:.2f} | {fmt(x['fgac_vs_native_pct'])} | [{x['ci_block3'][0]:+.2f}%, {x['ci_block3'][1]:+.2f}%] | {fmt(x['fgac_vs_inline_pct'])} |")
lines+=['','## 平均口径与稳定性','','| 集合 | 场景等权配对变化 | 总耗时比值变化 |','|---|---:|---:|']
for k,x in overall.items():lines.append(f"| {k} | {fmt(x['equal_case_mean_pct'])} | {fmt(x['sum_time_ratio_pct'])} |")
lines+=['','场景等权给予每个场景相同权重；总耗时比值更受慢场景影响。两者回答不同问题，不选择较好的一个替代另一个。','','| 场景 | 前12轮 | 中12轮 | 后12轮 |','|---|---:|---:|---:|']
for x in s:lines.append('| '+labels[x['case']]+' | '+' | '.join(fmt(v) for v in x['block12_means'])+' |')
lines+=['','## 对5%目标的解释','']
for name in ['bob_90','bob_100','whole_source_100']:
 x=by[name];status='本轮点估计和主置信区间上界均不超过+5%' if x['ci_block3'][1]<=5 else ('点估计不超过+5%，但主置信区间尚不能支持稳定达到目标' if x['fgac_vs_native_pct']<=5 else '本轮点估计仍高于+5%')
 lines.append(f"- {labels[name]}：{status}。")
lines+=['','上述判断仅针对本次单表四列工作负载和当前部署。即使全表场景满足目标，也不意味着所有数据集、复杂查询、引擎或分布式部署均达到5%。当前新增R适配只验证Spark3.5.8 local模式。','','## 与阶段结论的关系','','分区优化阶段比较的是同实例旧COLLECT与新STREAM交付，证明了首批提前和端到端改善；本轮比较的是最新FGAC与真实原生授权及inline，是另一个比较对象。不能把阶段改善百分比与本轮基线差异直接相加。','','高返回率下，分区内交付可以让R扫描、传输与E消费重叠。小结果集仍有Catalog、两端作业调度、IPC接入等固定成本，分区优化不会消除这些成本。具体判断以本轮逐场景表为准；压缩实验的带宽收益不能当作本轮延迟收益。','','## 资源与验证','','| 主机 | 正式窗口平均CPU | 约2秒采样峰值 | 平均iowait | 换入/换出页 |','|---|---:|---:|---:|---:|']
for role,x in load.items():lines.append(f"| {role} | {x['cpu_mean_pct']:.2f}% | {x['cpu_peak_pct']:.2f}% | {x['iowait_mean_pct']:.6f}% | {x['swapin_pages']}/{x['swapout_pages']} |")
lines += ['',f"正式查询{done['formal_records']}次，预热400次。验证覆盖{stage['query_groups']}个E/R查询组；失败任务/作业{stage['failed_tasks_or_jobs']}，内存spill {stage['memory_spill_bytes']:.0f}字节，磁盘spill {stage['disk_spill_bytes']:.0f}字节。",'', '仍有其他业务背景活动；全部样本保留，不能宣称完全无干扰。交错顺序、统一预热和分段复核降低了偏差，但本轮仍是一次持续会话内重复，置信区间不替代多次独立重启或其他数据集验证。','','## 服务状态与交付','','测试使用新隔离目录deploy/fgac-final-baseline、runs/final-baseline-0915。完成后清理测试进程，旧Catalog、Remote、MinIO及原18815服务保持运行，未切换原部署默认配置。凭据没有纳入发布材料。','','同目录提供summary.json/.csv、pairs.csv、overall.json、stage-validation.json、load-summary.json、final_comparison.png/.pdf及复现脚本。完整任务事件与资源证据保留在两机运行目录的evidence-R/E.tar.gz，并提供SHA-256。']
(p/'FINAL_PERFORMANCE_REPORT.md').write_text('\n'.join(lines),encoding='utf-8')
