import json,statistics,datetime
from pathlib import Path
p=Path(__file__).resolve().parent;s=json.loads((p/'summary.json').read_text());load=json.loads((p/'load-summary.json').read_text());records=json.loads((p/'verified-records.json').read_text())
assert all(x['probe']['queue_peak_batches']<=2 for x in records if x['mode']=='STREAM')
lines=['# 分区内 Arrow 逐批交付：实现与性能复测','', '结论：在当前 Spark 3.5.8 local[2] 部署中，已实现并验证分区内逐批交付。相对同一轮、同一R/E Spark实例的原收集路径，90%和授权集合100%场景端到端配对平均耗时分别下降约29.0%和34.1%。分区数量与批次大小未改变，消除了原路径先收集完整分区结果再交付的屏障。此结论不等同于新的Ranger基线对比。','', '## 实现','', '- 原路径：Spark Arrow批次生成 → 分区批次数组收集（it.toArray）→ Spark任务结果回传 → JVM到Python socket → Flight。','- 新路径：Spark Arrow批次生成 → 同一JVM中的有界队列 → JVM到Python socket → Flight。任务生成一批即可交付，不构建完整分区结果数组。','- 新增 streaming/jvm/PartitionArrowStream.java 和 Python适配函数；默认仍走原路径，FGAC_ARROW_DELIVERY=partition_stream 为可选开关。使用前需将helper jar追加至原有spark.jars，不能覆盖Iceberg等依赖。','- 共享队列最多2批，字节许可上限16 MiB；生产端和socket仍有在途缓冲，这不是进程总内存上限。超过16 MiB的单批会明确失败。','- 仅支持当前Spark 3.5 local模式；使用私有Spark API及同JVM注册表，拒绝推测执行。分布式executor尚未实现，不能直接启用。','- 每个分区仅接受首次任务尝试；重试导致整条流失败，避免重复发送已交付数据。失败不能被当成完整结果；消费者需丢弃部分结果。关闭消费者连接会取消对应Spark作业组。','- 外部Arrow Flight、Catalog权限检查、数据策略、schema与E端消费适配不变。没有结果落盘或新增数据缓存。','', '## 统一测试口径','', '- R=:10023、E=:10025；隔离目录deploy/fgac-partition-stream；COLLECT端口18830、STREAM端口18831。原18815和旧部署不变。','- 两路径共用一个R Spark JVM和一个E Spark JVM；两端仍为local[2]，沿用2 GiB堆配置，没有绑核或限制FGAC总计算资源。','- 每批8192行、无压缩、E预取2批/16 MiB。每个场景/模式预热20次、正式60次，总计80次预热＋240次正式查询。每场景两种执行顺序各30次，随机交错，种子91507。','- 场景：Bob90%返回2,011,899行；Bob授权集合100%返回2,234,632行。后者不是原始全表100%。读取相同四列。','- 端到端计时包含准备、完整四列count和双xxhash64摘要消费、流完成与关闭；结果均与之前Ranger原生结果一致。快照6896028106384817739在开始、每10轮、结束检查。','- 本轮没有重新执行Ranger延迟测量，因此不能与历史Ranger时间拼接，也不能据此宣称达到5%目标。','- 5000次循环块bootstrap，主区间块长5，并用块长10复核；另检查三个20轮时间段。全部正式样本保留，不按性能结果删样本。','', '## 性能结果','', '耗时列为中位数；百分比为同轮配对比值的平均值，两者计算口径不同。负数表示STREAM更快。','', '| 场景 | 原COLLECT ms | 新STREAM ms | 配对变化 | 95%区间 |','|---|---:|---:|---:|---|']
for x in s:lines.append(f"| {x['case']} | {x['collect']['total_ms']:.2f} | {x['stream']['total_ms']:.2f} | {x['paired_mean_delta_pct']:.2f}% | [{x['ci_block5'][0]:.2f}, {x['ci_block5'][1]:.2f}]% |")
lines+=['','| 场景 | 前20轮变化 | 中20轮变化 | 后20轮变化 |','|---|---:|---:|---:|']
for x in s:lines.append('| '+x['case']+' | '+' | '.join(f'{v:.2f}%' for v in x['block20_means'])+' |')
lines+=['','两个场景等权的配对平均改善约31.53%。这是相对本轮旧交付路径的改善，不是相对原生基线。各段方向一致，块长10区间同样完全小于零；仍只代表一次持续JVM会话内的重复实验，不是多次独立部署实验。','', '## 是否真正消除了分区屏障？','', '| 场景 | E首批：旧→新 ms | R首批写出 ms | R首分区完成 ms | 正式扫描中首批先写出 |','|---|---|---:|---:|---:|']
for x in s:lines.append(f"| {x['case']} | {x['collect']['first_arrow_ms']:.2f} → {x['stream']['first_arrow_ms']:.2f} | {x['probe']['first_written_ms']:.2f} | {x['probe']['first_partition_done_ms']:.2f} | {x['first_write_before_first_partition_count']}/60 |")
lines+=['','R探针以helper创建为起点，E首批时间以查询计时起点为起点，不能直接相减。全部120次正式STREAM扫描都在首个分区完成前写出首批数据；共享队列峰值不超过2批。两路径仍是3个扫描任务、相同源输入2,964,624行，结果批次数仍为248/275，逻辑Arrow字节仍为56,333,172/62,569,696。没有依靠缩减扫描数据或改变业务语义获得收益。','','## 为什么整体更快？','','原路径把同一分区的所有批次汇总为任务结果，再交付给Python。新路径让授权扫描、跨进程交付、Flight传输和E消费更早重叠，同时绕过分区结果数组收集与任务结果回传，因此不能把全部收益只归因于一个等待计时器。','','Bob100%下，E任务运行时间之和中位数约1841→1144.5ms，但任务CPU约929→935ms，说明实际消费计算量没有明显减少，等待时间下降。R任务CPU约714→708ms，同样接近；任务GC时间之和中位数约51→20ms，伴随较少的分区结果缓冲。任务时间可跨并行任务重叠，不能直接作为查询墙钟耗时相加。','','R进程CPU探针也有下降，但它包含JVM GC、JIT、驱动端和Python工作，并非纯扫描CPU；与任务CPU口径不同。本轮尚未分别量化收集、任务结果序列化和GC各自贡献。','','## 可靠性与背景负载','','- 全部320次完整查询行数、schema与双摘要校验通过；2个无效身份控制测试通过。','- 640个E/R查询组无任务/作业失败、无内存或磁盘spill。','- 新增生成数据集成检查通过：首批先于分区完成、有界队列、空结果、取消、生产端错误传播、失败后恢复、错误本地令牌拒绝。注入异常是预期测试，不计入性能运行失败。','- 原有41项streaming单元测试全部通过。','', '| 主机 | 平均CPU | 约2秒采样峰值 | 平均iowait | 换入/换出页 |','|---|---:|---:|---:|---:|']
for role,x in load.items():lines.append(f"| {role} | {x['cpu_mean_pct']:.2f}% | {x['cpu_peak_pct']:.2f}% | {x['iowait_mean_pct']:.6f}% | {x['swapin_pages']}/{x['swapout_pages']} |")
lines+=['','R侧仍有Doris及其他Java进程，E侧有其他存储、容器活动；不能宣称背景完全无干扰。采用同实例、交错顺序和分段复核降低偏差。原始每进程、每核、I/O、网络与压力数据保留在证据中；两秒采样可能漏掉短命进程。','','## 启动修正与清理','','首次隔离启动用--jars指定helper，覆盖了原spark.jars中的Iceberg依赖，导致首条预热查询计划解析失败。修正为追加helper并验证两个端点都能解析表后，从完整预热重新开始。首次没有正式性能样本，记录保留在initial-*中；上表仅来自修正后的完整运行。','','测试结束后E测试worker停止。R隔离进程组SIGTERM后Java退出，Python多端点关闭未退出，核实路径后仅终止隔离Python。原FGAC PID2096673/JVM2096447保持运行；旧Catalog、Remote、MinIO健康检查均200，旧进程启动标识未变。存储仍只有staging/warehouse。没有改动原部署的默认参数。','','## 交付物与下一步','','代码位于仓库streaming/spark_batches.py、streaming/jvm/PartitionArrowStream.java、streaming/test_partition_integration.py，README包含构建和启用说明。编译产物partition-arrow-stream.jar、图表partition_stream.png/.pdf、原始证据evidence-R/E.tar.gz、分析脚本和汇总同本报告目录。','','建议下一步在确认当前本地R部署继续采用该适配后，同轮重新加入Ranger及理论上限对照，再判断最终FGAC劣化率。不要用本轮STREAM耗时直接对比前几轮原生耗时。分布式R场景需实现独立的executor传输和失败语义适配。']
(p/'PARTITION_STREAM_REPORT.md').write_text('\n'.join(lines),encoding='utf-8')
