FROM postgres:16-alpine
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
    && apk add --no-cache build-base
WORKDIR /build
COPY plugins/postgres/Makefile plugins/postgres/fgac_pg.c ./
RUN make with_llvm=no
CMD ["sh", "-c", "cp /build/fgac_pg.so /artifacts/fgac_pg.so"]
